INSERT INTO rooms (room_name, capacity, access_level, room_status)
VALUES 
    -- Building A rooms --
    ('A-ELab-Co-working-Space', 50, 'ALL_USERS', 'AVAILABLE'),
    ('A101-247-Learning-Space', 72, 'ALL_USERS', 'AVAILABLE'),
    ('A102-Group-Discussion-Room', 8, 'ALL_USERS', 'AVAILABLE'),
    ('A103-Group-Discussion-Room', 8, 'ALL_USERS', 'AVAILABLE'),
    ('A104-Group-Discussion-Room', 4, 'ALL_USERS', 'AVAILABLE'),
    ('A105-Group-Discussion-Room', 4, 'ALL_USERS', 'AVAILABLE'),
    ('A106-Group-Discussion-Room', 8, 'ALL_USERS', 'AVAILABLE'),
    ('A107-Group-Discussion-Room', 8, 'ALL_USERS', 'AVAILABLE'),
    ('A108-Group-Discussion-Room', 8, 'ALL_USERS', 'AVAILABLE'),
    ('A109-Group-Discussion-Room', 8, 'ALL_USERS', 'AVAILABLE'),
    ('A110-Group-Discussion-Room', 5, 'ALL_USERS', 'AVAILABLE'),
    ('A111-Group-Discussion-Room', 8, 'ALL_USERS', 'AVAILABLE'),
    ('A112-Group-Discussion-Room', 5, 'ALL_USERS', 'AVAILABLE'),
    ('A113-Group-Discussion-Room', 10, 'ALL_USERS', 'AVAILABLE'),
    ('A114-Group-Discussion-Room', 8, 'ALL_USERS', 'AVAILABLE'),
    ('A117-Multipurpose-Classroom', 30, 'ALL_USERS', 'AVAILABLE'),
    ('A122-Brainstorm-Space-Meeting-Room', 10, 'ALL_USERS', 'AVAILABLE'),
    ('A123-Synergy-Station-Meeting-Room', 6, 'ALL_USERS', 'AVAILABLE'),
    ('A124-Focus-Corner-Meeting-Room', 6, 'ALL_USERS', 'AVAILABLE'),
    ('A128-Design-Thinking-Meeting-Room', 20, 'ALL_USERS', 'AVAILABLE'),
    ('A202-Semi-Pro-Studio', 6, 'ALL_USERS', 'AVAILABLE'),
    ('A203-One-Button-Studio', 6, 'ALL_USERS', 'AVAILABLE'),
    ('A205-Writing-Lab', 9, 'ALL_USERS', 'AVAILABLE'),
    ('A206-Video-Editing-Room', 4, 'ALL_USERS', 'AVAILABLE'),
    ('A207-VR-Room', 2, 'ALL_USERS', 'AVAILABLE'),
    ('A210-Library-Meeting-Room', 10, 'ALL_USERS', 'AVAILABLE'),
    ('A212-Group-Discussion-Room', 3, 'ALL_USERS', 'AVAILABLE'),
    ('A213-Group-Discussion-Room', 3, 'ALL_USERS', 'AVAILABLE'),
    ('A214-Group-Discussion-Room', 3, 'ALL_USERS', 'AVAILABLE'),
    ('A215-Group-Discussion-Room', 3, 'ALL_USERS', 'AVAILABLE'),
    ('A216-Group-Discussion-Room', 6, 'ALL_USERS', 'AVAILABLE'),
    ('A217-Group-Discussion-Room', 6, 'ALL_USERS', 'AVAILABLE'),
    ('A218-Prayer-Room', 4, 'ALL_USERS', 'AVAILABLE'),
    ('A3-Babylon-Garden', 200, 'ALL_USERS', 'AVAILABLE'),
    -- Building B rooms -- 
    ('B-Outdoor-Amphitheater', 100, 'ALL_USERS', 'AVAILABLE'),
    -- Building C rooms --
    ('C101-TBL-Classroom', 42, 'ALL_USERS', 'AVAILABLE'),
    ('C102-Multipurpose-Classroom', 100, 'ALL_USERS', 'AVAILABLE'),
    ('C104-Multipurpose-Classroom', 50, 'ALL_USERS', 'AVAILABLE'),
    ('C105-TBL-Classroom', 42, 'ALL_USERS', 'AVAILABLE'),
    ('C201-TBL-Classroom', 56, 'ALL_USERS', 'AVAILABLE'),
    ('C202-Lecture-Hall', 75, 'ALL_USERS', 'AVAILABLE'),
    ('C203-TBL-Classroom', 56, 'ALL_USERS', 'AVAILABLE'),
    ('C204-TBL-Classroom', 50, 'ALL_USERS', 'AVAILABLE'),
    ('C205-Multipurpose-Classroom', 24, 'ALL_USERS', 'AVAILABLE'),
    ('C301-AB-Multipurpose-Classroom', 60, 'ALL_USERS', 'AVAILABLE'),
    ('C302-Multipurpose-Classroom', 56, 'ALL_USERS', 'AVAILABLE'),
    ('C303-Multipurpose-Classroom', 60, 'ALL_USERS', 'AVAILABLE'),
    ('C304-TBL-Classroom', 50, 'ALL_USERS', 'AVAILABLE'),
    ('C305-TBL-Classroom', 50, 'ALL_USERS', 'AVAILABLE'),
    ('C401-TBL-Classroom', 231, 'ALL_USERS', 'AVAILABLE'),
    ('C402-Multipurpose-Classroom', 60, 'ALL_USERS', 'AVAILABLE'),
    -- Building D rooms --
    ('D210-Meeting-Room', 8, 'STAFF_ONLY', 'AVAILABLE'),
    ('D211-Meeting-Room', 8, 'STAFF_ONLY', 'AVAILABLE'),
    ('D212-Green-Meeting-Room', 18, 'STAFF_ONLY', 'AVAILABLE'),
    ('D301-Lecture', 112, 'ALL_USERS', 'AVAILABLE'),
    ('D302-Lecture', 154, 'ALL_USERS', 'AVAILABLE'),
    ('D303-ActiveLearning-Classroom', 52, 'ALL_USERS', 'AVAILABLE'),
    ('D304-ActiveLearning-Classroom', 52, 'ALL_USERS', 'AVAILABLE'),
    ('D305-ActiveLearning-Classroom', 52, 'ALL_USERS', 'AVAILABLE'),
    -- Building E rooms --
    ('E401-Multipurpose-Classroom', 30, 'ALL_USERS', 'AVAILABLE'),
    ('E402-Multipurpose-Classroom', 100, 'ALL_USERS', 'AVAILABLE'),
    ('E403-Multipurpose-Classroom', 184, 'ALL_USERS', 'AVAILABLE'),
    -- Building F rooms --
    ('F307-Virtual-Lab', 80, 'ALL_USERS', 'AVAILABLE'),
    ('F310-Meeting-Room', 12, 'STAFF_ONLY', 'AVAILABLE'),
    -- Building G rooms --
    ('G102-Super-Lab', 118, 'ALL_USERS', 'AVAILABLE'),
    ('G104-Multipurpose-Classroom', 100, 'ALL_USERS', 'AVAILABLE'),
    ('G201-Multipurpose-Classroom', 40, 'ALL_USERS', 'AVAILABLE'),
    ('G204-Multipurpose-Classroom', 30, 'ALL_USERS', 'AVAILABLE'),
    ('G205-Computer-Lab', 36, 'ALL_USERS', 'AVAILABLE'),
    ('G207-Computer-Lab', 54, 'ALL_USERS', 'AVAILABLE'),
    ('G208-Mechatronics-Control-Lab', 30, 'ALL_USERS', 'AVAILABLE'),
    ('G209-FMS-CIM-Lab', 20, 'ALL_USERS', 'AVAILABLE'),
    ('G210-Communication-Network-Lab', 20, 'ALL_USERS', 'AVAILABLE'),
    -- Building H rooms --
    ('H-Outdoor-Pickleball-Field-A', 4, 'ALL_USERS', 'AVAILABLE'),
    ('H-Outdoor-Pickleball-Field-B', 4, 'ALL_USERS', 'AVAILABLE'),
    -- Building I rooms --
    ('I-Welcome-Flip-TV', 2, 'ALL_USERS', 'AVAILABLE'),
    ('I108-Discussion-Room (SE Hub)', 6, 'ALL_USERS', 'AVAILABLE'),
    ('I109-Discussion-Room (SE Hub)', 6, 'ALL_USERS', 'AVAILABLE'),
    ('I110-Discussion-Room (SE Hub)', 6, 'ALL_USERS', 'AVAILABLE'),
    ('I111-CareerServices', 6, 'ALL_USERS', 'AVAILABLE'),
    ('I112-Meeting-Room', 6, 'STAFF_ONLY', 'AVAILABLE'),
    ('I120-InternationalSupportCenter', 6, 'ALL_USERS', 'AVAILABLE'),
    ('I2-Atrium-Lobby', 100, 'ALL_USERS', 'AVAILABLE'),
    ('I2-Scale-model-space', 80, 'ALL_USERS', 'AVAILABLE'),
    ('I201-Peace-Room', 6, 'STAFF_ONLY', 'AVAILABLE'),
    ('I207-DaVinci-Meeting-Room', 22, 'STAFF_ONLY', 'AVAILABLE'),
    ('I305-Meeting-Room', 12, 'STAFF_ONLY', 'AVAILABLE'),
    ('I314-QuickMeeting-Room', 6, 'STAFF_ONLY', 'AVAILABLE'),
    ('I319-EinStein-Meeting-Room', 16, 'STAFF_ONLY', 'AVAILABLE'),
    ('I319A-Newton-Meeting-Room', 8, 'STAFF_ONLY', 'AVAILABLE'),
    ('I414-Conference-Room-1', 6, 'ALL_USERS', 'AVAILABLE'),
    ('I417-Conference-Room-4', 6, 'ALL_USERS', 'AVAILABLE'),
    ('I418-ThomasEdison-Meeting-Room', 6, 'STAFF_ONLY', 'AVAILABLE'),
    ('I419-LouisPasteur-Meeting-Room', 6, 'STAFF_ONLY', 'AVAILABLE'),
    ('I420-Hippocrates-Meeting-Room', 16, 'STAFF_ONLY', 'AVAILABLE'),
    ('I421-MarieCurie-Meeting-Room', 16, 'STAFF_ONLY', 'AVAILABLE'),
    ('I422-Conference-Room-5', 6, 'ALL_USERS', 'AVAILABLE'),
    ('I506-Meeting-Room', 8, 'STAFF_ONLY', 'AVAILABLE'),
    ('I507-Meeting-Room', 4, 'STAFF_ONLY', 'AVAILABLE'),
    ('I508-Meeting-Room', 8, 'STAFF_ONLY', 'AVAILABLE'),
    ('I509-Meeting-Room', 8, 'STAFF_ONLY', 'AVAILABLE'),
    ('I510-Meeting-Room', 4, 'STAFF_ONLY', 'AVAILABLE'),
    ('I514-Meeting-Room', 8, 'STAFF_ONLY', 'AVAILABLE'),
    ('I522-Meeting-Room', 4, 'STAFF_ONLY', 'AVAILABLE'),
    ('I524-Meeting-Room', 4, 'STAFF_ONLY', 'AVAILABLE'),
    ('I526-Meeting-Room', 4, 'STAFF_ONLY', 'AVAILABLE'),
    ('I527-Meeting-Room', 16, 'STAFF_ONLY', 'AVAILABLE'),
    ('I605-Meeting-Room', 8, 'STAFF_ONLY', 'AVAILABLE'),
    ('I606-Meeting-Room', 4, 'STAFF_ONLY', 'AVAILABLE'),
    ('I609-Meeting-Room', 4, 'STAFF_ONLY', 'AVAILABLE'),
    ('I613-Meeting-Room', 4, 'STAFF_ONLY', 'AVAILABLE'),
    ('I1901-Lomonosov-Meeting-Room', 16, 'STAFF_ONLY', 'AVAILABLE'),
    -- Building J rooms --
    ('JA102-Meeting-Room', 48, 'ALL_USERS', 'AVAILABLE'),
    ('JB109-Dance-Room', 10, 'ALL_USERS', 'AVAILABLE'),
    ('JB110-Meeting-Room', 24, 'ALL_USERS', 'AVAILABLE'),
    ('JB111-Meeting-Room', 30, 'ALL_USERS', 'AVAILABLE'),
    -- Building K rooms --
    ('K101-Sport-Complex', 200, 'ALL_USERS', 'AVAILABLE'),
    ('K104-Yoga-Room', 12, 'ALL_USERS', 'AVAILABLE'),
    ('K201-Kendo-Room', 30, 'ALL_USERS', 'AVAILABLE'),
    ('K202-Dance-Room', 30, 'ALL_USERS', 'AVAILABLE'),
    ('K203-Music-Room', 10, 'ALL_USERS', 'AVAILABLE'),
    -- Building L rooms --
    ('L-Outdoor-Football-Field-A', 7, 'ALL_USERS', 'AVAILABLE'),
    ('L-Outdoor-Football-Field-B', 7, 'ALL_USERS', 'AVAILABLE'),
    ('L-Outdoor-Tennis-Court', 4, 'ALL_USERS', 'AVAILABLE'),
    ('L-Outdoor-Volleyball-Basketball-Court', 10, 'ALL_USERS', 'AVAILABLE')
;